ci: run staging e2e tests

diff --git a/.github/workflows/03-deploy-staging.yml b/.github/workflows/03-deploy-staging.yml
--- a/.github/workflows/03-deploy-staging.yml
+++ b/.github/workflows/03-deploy-staging.yml
@@ -59,7 +59,7 @@ jobs:
           echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> .env
           echo "DATABASE_URL_STAG=${{ secrets.DATABASE_URL_STAG }}" >> .env
 
-      - name: Configure SSH
+      - name: Configure SSH ffor EC2 Access
         uses: webfactory/ssh-agent@v0.9.0
         with:
           ssh-private-key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
@@ -74,6 +74,7 @@ jobs:
           scp docker-compose.stag.yml ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }}:/home/ubuntu/coding-app/docker-compose.stag.yml
           ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} "\
             cd /home/ubuntu/coding-app && \
+            git pull origin main && \
             docker-compose --env-file .env -f docker-compose.stag.yml pull && \
             docker-compose --env-file .env -f docker-compose.stag.yml up --build -d"
 
@@ -85,6 +86,55 @@ jobs:
         run: |
           echo "GitHub SHA: ${{ github.sha }}"
 
+      - name: Common Setup on Staging Server
+        run: |
+          ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
+            echo "Switching to project directory..."
+            cd /home/ubuntu/coding-app
+            pwd
+
+            echo "Loading nvm environment..."
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+
+            echo "Verifying Node.js and npm versions..."
+            node --version
+            npm --version
+          EOF
+
+      - name: Run Unit Tests on Staging Server
+        run: |
+            ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
+              echo "Running Unit Tests..."
+              export NVM_DIR="$HOME/.nvm"
+              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+
+              cd /home/ubuntu/coding-app/server
+              echo "Running unit tests in /server..."
+              npm install
+              npm run test:unit:ci || exit 1
+
+              cd /home/ubuntu/coding-app/client
+              echo "Running unit tests in /client..."
+              npm install
+              npm run test:unit:ci || exit 1
+
+              echo "Unit tests passed successfully!"
+            EOF
+
+      - name: Run E2E Tests on Staging Server
+        run: |
+          ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
+            echo "Running E2E tests..."
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+
+            cd /home/ubuntu/coding-app
+            npm run test:e2e || exit 1
+
+            echo "E2E tests passed successfully!"
+          EOF
+
       - name: Clean Up Docker Resources on EC2
         run: |
           ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
@@ -92,26 +142,74 @@ jobs:
             docker system prune -af
             echo "Docker cleanup completed!"
             df -h
-          EOF
+          EOF    
 
-      # run tests
-      - name: Run E2E Tests on Staging Server
-        run: |
-          ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
-            echo "Switching to project directory..."
-            cd /home/ubuntu/coding-app    
+          
+      # # run tests
+      # - name: Run Unit Tests on Staging Server
+      #   run: |
+      #     ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
+      #       echo "Switching to project directory..."
+      #       cd /home/ubuntu/coding-app
+      #       pwd
 
-            echo "Running E2E tests..."
-            npm run test:e2e
-            EXIT_CODE=$?
+      #       echo "Loading nvm environment..."
+      #       export NVM_DIR="$HOME/.nvm"
+      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
 
-            if [ $EXIT_CODE -ne 0 ]; then
-              echo "E2E tests failed! Exit code: $EXIT_CODE"
-              exit $EXIT_CODE
-            else
-              echo "E2E tests passed successfully!"
-            fi
-          EOF
+      #       echo "Verifying Node.js and npm versions..."
+      #       node --version
+      #       npm --version
+
+      #       # Run Unit Tests in /server
+      #       echo "Running Unit Tests in /server..."
+      #       cd /home/ubuntu/coding-app/server
+      #       npm install
+      #       npm run test:unit:ci
+      #       SERVER_EXIT_CODE=$?
+
+      #       # Run Unit Tests in /client
+      #       echo "Running Unit Tests in /client..."
+      #       cd /home/ubuntu/coding-app/client
+      #       npm install
+      #       npm run test:unit:ci
+      #       CLIENT_EXIT_CODE=$?
+
+      #       # Check if Unit Tests Failed
+      #       if [ $SERVER_EXIT_CODE -ne 0 ] || [ $CLIENT_EXIT_CODE -ne 0 ]; then
+      #         echo "Unit tests failed! Exiting with error."
+      #         exit 1
+      #       else
+      #         echo "Unit tests passed successfully!"
+      #       fi
+      #     EOF
+
+      # - name: Run E2E Tests on Staging Server
+      #   run: |
+      #     ssh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
+      #       echo "Switching to project directory..."
+      #       cd /home/ubuntu/coding-app
+      #       pwd
+
+      #       echo "Loading nvm environment..."
+      #       export NVM_DIR="$HOME/.nvm"
+      #       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+
+      #       echo "Verifying Node.js and npm versions..."
+      #       node --version
+      #       npm --version
+
+      #       echo "Running E2E tests..."
+      #       /home/ubuntu/.nvm/versions/node/v22.12.0/bin/npm run test:e2e
+      #       EXIT_CODE=$?
+
+      #       if [ $EXIT_CODE -ne 0 ]; then
+      #         echo "E2E tests failed! Exit code: $EXIT_CODE"
+      #         exit $EXIT_CODE
+      #       else
+      #         echo "E2E tests passed successfully!"
+      #       fi
+      #     EOF
 
     # if ok, --> deploy to PROD
 
